version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: firesubz
      POSTGRES_PASSWORD: password
      POSTGRES_DB: firesubz
    volumes:
      - ./data:/var/lib/postgresql/data