CREATE TABLE "firesubz_notifications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "firesubz_notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"title" varchar(255) NOT NULL,
	"message" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"readAt" timestamp with time zone,
	"type" varchar(50)
);
--> statement-breakpoint
ALTER TABLE "firesubz_notifications" ADD CONSTRAINT "firesubz_notifications_userId_firesubz_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."firesubz_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_notifications_user_id" ON "firesubz_notifications" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "idx_notifications_created_at" ON "firesubz_notifications" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "idx_notifications_user_id_read" ON "firesubz_notifications" USING btree ("userId","readAt");