CREATE TABLE "firesubz_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "firesubz_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "firesubz_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "firesubz_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "firesubz_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "firesubz_subscription" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "firesubz_subscription_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"price" real NOT NULL,
	"currency" text DEFAULT 'USD',
	"frequency" text,
	"category" text NOT NULL,
	"paymentMethod" text NOT NULL,
	"status" text DEFAULT 'active',
	"startDate" timestamp with time zone NOT NULL,
	"renewalDate" timestamp with time zone,
	"userId" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "firesubz_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "firesubz_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "firesubz_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "firesubz_account" ADD CONSTRAINT "firesubz_account_userId_firesubz_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."firesubz_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "firesubz_post" ADD CONSTRAINT "firesubz_post_createdById_firesubz_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."firesubz_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "firesubz_session" ADD CONSTRAINT "firesubz_session_userId_firesubz_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."firesubz_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "firesubz_subscription" ADD CONSTRAINT "firesubz_subscription_userId_firesubz_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."firesubz_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "firesubz_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "firesubz_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "firesubz_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "firesubz_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "subscription_name_idx" ON "firesubz_subscription" USING btree ("name");--> statement-breakpoint
CREATE INDEX "price_idx" ON "firesubz_subscription" USING btree ("price");--> statement-breakpoint
CREATE INDEX "start_date_idx" ON "firesubz_subscription" USING btree ("startDate");--> statement-breakpoint
CREATE INDEX "renewal_date_idx" ON "firesubz_subscription" USING btree ("renewalDate");